#!/bin/bash

# Activate conda environment and run oculizer with etna profile
eval "$(conda shell.bash hook)"
conda activate oculizer
python oculize.py -p etna --prediction-device scarlett --single-stream
